mne-tools/mne-icalabel

ICLabel.py
mne_icalabel/tests/tests_ica_features.py

@jacobf18 Great start.
I took a look and ran things locally. Without a test file explicitly ran through EEGLab Matlab, hard to see what "differs". 
There's a few easy changes that I would like you to make, that will facilitate discussion on Monday:
- adding docstrings and some inline comments to `mne_to_eeglab_locs`. This function seems like it wouldn't change too much, so it'll be good to aggressively document what is going on and any description for obscure-like logic. You'll see I added "TODO" comments in various places.
- it'd be good to describe what `format_input()` is doing as well.
- as mentioned in slack, please run MATLAB version through for `eeglab_data_epochs_ica.set` sample data, saving the outputs of each step. We can then i) make our output match that of Matlab's as much as …

Add questions via code

---

mne_icalabel/assets/network_sample_output.m

MATLAB script  used to generate the input/output.
Thanks for contributing. If this is your first time,
make sure to read the [contributing guide.](https://github.com/mne-tools/mne-python/blob/main/CONTRIBUTING.md)
PR Description
--------------
Describe your PR here

Adding MATLAB sample output

---

.circleci/config.yml
Makefile
README.md
doc/index.rst

Fix docs from adam2392 -> mne.tools

---

.circleci/config.yml
.github/workflows/unit_tests.yml
doc/install.rst
mne_icalabel/conftest.py
mne_icalabel/datasets/icalabel/icalabel.py
mne_icalabel/iclabel/__init__.py
mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/network.py
mne_icalabel/iclabel/utils.py
requirements.txt
requirements_testing.txt
setup.cfg

Closes: #46
Closes: #47
Closes: #48
Closes: #52

Fix requirements and python version

---

.gitignore
doc/install.rst

PR Description
--------------
Closes: #50 
Closes: #51 

[DOC] Fix installation instructions

---

doc/whats_new.rst
mne_icalabel/datasets/icalabel/icalabel.py
mne_icalabel/datasets/icalabel/tests/test_dataset_icalabel.py
mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/tests/test_features.py
mne_icalabel/iclabel/tests/test_label_components.py
mne_icalabel/iclabel/tests/test_utils.py

Closes #38
Closes #63 
The PSD constants are correct and the issue lies here: https://github.com/mne-tools/mne-icalabel/blob/ecc6a917e9540acdaf148845a145c882fcfc3b26/mne_icalabel/iclabel/features.py#L315-L316

[BUG] Fix the PSD features of ICLabel with epochs of more than 1 second

---

.circleci/config.yml
README.md

FIX CI Rebasing

---

doc/conf.py
doc/whats_new.rst
mne_icalabel/_version.py
mne_icalabel/datasets/icalabel/icalabel.py
mne_icalabel/datasets/tests/test_icalabel.py
mne_icalabel/features/tests/test_topomap.py
mne_icalabel/features/topomap.py
mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/label_components.py
mne_icalabel/iclabel/network.py
mne_icalabel/iclabel/tests/test_label_components.py
mne_icalabel/label_components.py
mne_icalabel/tests/test_label_components.py
mne_icalabel/utils/_checks.py
mne_icalabel/utils/_docs.py
mne_icalabel/utils/tests/test_checks.py
mne_icalabel/utils/tests/test_docs.py
pyproject.toml

First step for #93.
It's just a start for now ;)

[MNT] Improve coverage

---

doc/api.rst
doc/conf.py
examples/label_components.py
mne_icalabel/gui/__init__.py

PR Description
--------------
Adds the GUI to docs and adds some extra text to the example to warn users of possibly buggy behavior.

[DOCS] Add docs for gui

---

.circleci/config.yml
.github/workflows/unit_tests.yml
doc/Makefile
doc/conf.py
doc/whats_new.rst
examples/README.txt
mne_icalabel/datasets/icalabel/icalabel.py

PR Description
--------------
Closes: #90 

[RELEASE] V0.3

---

pyproject.toml

Fixes #99 
@adam2392 I tested it locally, the build does include the file now.

[BUG] Include '.pt' file in the distribution

---

doc/index.rst

[DOC] Fix website link to license

---

doc/conf.py

[DOC] Replace sphinx.ext.viewcode with sphinx.ext.linkcode

---

Makefile
doc/whats_new.rst
mne_icalabel/annotation/bids.py
mne_icalabel/iclabel/utils.py

Closes #89 
PR Description
--------------
Fix some minor issue in the BIDS pipeline.

[ENH] BIDS Annotating pipeline

---

doc/_static/style.css
doc/conf.py

Updated `conf.py` and `style.css` based on what I found on MNE main.

[DOC] Use the mne-python style.css for better light/dark theme support

---

doc/api.rst
examples/iclabel_automatic_artifact_correction_ica.py
mne_icalabel/iclabel/label_components.py
mne_icalabel/label_components.py

Improve description of supported datatypes by ICLabel

---

examples/label_components.py
mne_icalabel/gui/__init__.py

PR Description
--------------
Fixes: #103 

Add error messages for GUI for QT bindings

---

doc/conf.py
doc/whats_new.rst
pyproject.toml

PR Description
--------------
Makes v0.4 release for JOSS

v0.4 release

---

.codecov.yml
.github/workflows/draft-pdf.yml
.github/workflows/unit_tests.yml
CITATION.cff
README.md
doc/index.rst
pyproject.toml

Fix codecov

---

doc/Makefile
doc/_templates/autosummary/class.rst
doc/_templates/autosummary/function.rst
doc/conf.py
doc/index.rst
doc/install.rst
doc/links.inc
doc/references.bib
examples/00_iclabel.py
examples/10_gui_label_components.py
examples/README.rst
examples/README.txt
mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/label_components.py
mne_icalabel/iclabel/network.py
pyproject.toml

Closes #117 
Let's see if that still builds 😄

[DOC] Improve documentation configuration

---

.github/workflows/unit_tests.yml

PR Description
--------------
Fixes GH actions. 
Feel free to merge if this makes it go green :) 

[CI] Fix GHActions for MNE-BIDs main

---

doc/changes/latest.rst
mne_icalabel/gui/_label_components.py

Remove the splash screen following https://github.com/mne-tools/mne-python/pull/12185

Remove splash screen in GUI in MNE 1.6 and above

---

pyproject.toml

Fix missing dep for stubs workflow

---

doc/_static/versions.json
doc/changes/index.rst
doc/changes/latest.rst
pyproject.toml

Merge after release is complete.

Bump to dev release

---

.codecov.yaml
doc/conf.py

Fix codecov configuration
