mne-tools/mne-icalabel

.github/ISSUE_TEMPLATE/blank.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/circle_artifacts.yml
.github/workflows/unit_tests.yml
Makefile
README.md
examples/README.txt
examples/automatic_artifact_correction_ica.py
mne_icalabel/__init__.py
requirements_doc.txt

Not sure if the CIs are enabled on this PR until it merges in... but here's a try.
Note that I think to shorten the later-on work of turning this into a robust API, I would just develop the API necessary within the `mne_icalabel/` directory, so that `setup.py/cfg` can package it neatly down the line.
Didn't change anything related to code though, so once you have things working, lmk. We can clean up the repo and try to make the CIs pass

Enable ci setup

---

mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/tests/test_features.py

It looks like I got it right in #21.
WDYT?

Improve testing for resampling in the autocorrelation feature

---

doc/api.rst
doc/index.rst
doc/install.rst
doc/sphinxext/gh_substitutions.py
doc/whats_new_previous_releases.rst
mne_icalabel/label_components.py

Some minor doc improvements. in `API.rst`, I would rework this paragraph as well:
> The model has three inputs: image, psd, and autocorrelation features. To encourage generalization, the image
> features are rotated and negated, thus quadrupling the feature. The psd and autocorrelation features
> are copied to the new image features. Then, the predicted probabilities are averaged over all four images.

Doc improvements

---

mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/label_components.py
mne_icalabel/iclabel/tests/test_features.py
mne_icalabel/iclabel/tests/test_label_components.py
mne_icalabel/iclabel/tests/test_utils.py
mne_icalabel/iclabel/utils.py
mne_icalabel/label_components.py
mne_icalabel/tests/test_label_components.py
mne_icalabel/tests/test_utils.py
mne_icalabel/utils.py

I fixed the FutureWarning by adding `rcond=-1` to keep the old behavior which seems to match with MATLAB.
I also added some error checking for the arguments provided to the public functions.
-> `mne_icalabel/utils.py`: functions and error checking that could be used for all models.
-> `mne_icalabel/iclabel/features:get_iclabel_features`: I added additional error checking for ICLabel here, using the MNE logger/warning. I did not add it to `mne_icalabel/iclabel/label_components`, since it will have to run through `get_iclabel_features` anyway.

Fix FutureWarning and add some error checking and warnings

---

doc/conf.py
examples/iclabel_automatic_artifact_correction_ica.py
mne_icalabel/iclabel/__init__.py
mne_icalabel/iclabel/config.py
mne_icalabel/iclabel/label_components.py
mne_icalabel/iclabel/network.py
mne_icalabel/iclabel/tests/test_label_components.py
mne_icalabel/label_components.py

PR Description
--------------
Addresses #5 and #19

[ENH] Moredocs and experiment with api implementation

---

doc/whats_new.rst
mne_icalabel/label_components.py
mne_icalabel/tests/test_label_components.py

Previous selection would return a square matrix, e.g. if 15 components were provided, we would go from `(15, 7)` shape to `(15, 15)` instead of `(15, )`.

Fix probabilities returned by label_components

---

.gitignore
README.md
doc/install.rst

PR Description
--------------
Describe your PR here

Fix previous PR Docs

---

doc/whats_new.rst
mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/tests/test_label_components.py

As pointed out by @jacobf18 in https://github.com/mne-tools/mne-icalabel/pull/40#issuecomment-1120450589
I added a warning if the ICA provided is not using an extended infomax + test for this warning and the 2 previously added warnings if the raw|epochs instance was not filtered between [1, 100] Hz or referenced to a common average.

Add warning if the ICA decomposition provided to ICLabel is not using an extended infomax

---

mne_icalabel/iclabel/tests/test_label_components.py

I replaced the random data array with 3 sources measured across 6 channels.
It should prevent convergence issues and be faster.

Improve and speed-up test for warnings in ICLabel

---

README.md
doc/api.rst
doc/conf.py
doc/whats_new.rst
mne_icalabel/annotation/__init__.py
mne_icalabel/annotation/bids.py
mne_icalabel/annotation/tests/test_bids.py
mne_icalabel/config.py
mne_icalabel/iclabel/config.py
mne_icalabel/label_components.py
requirements_testing.txt

PR Description
--------------
Addresses the API needed for the annotation GUI to interface with BIDS files of #12 

[ENH] Add API for bids pipeline annotating

---

.github/workflows/unit_tests.yml

The Paper Draft workflow was duplicated between `draft-pdf.yml` and `unit_test.yml`.

[PAPER] Remove duplicate workflow

---

doc/whats_new.rst
mne_icalabel/iclabel/features.py
mne_icalabel/iclabel/tests/test_features.py
mne_icalabel/iclabel/tests/test_label_components.py
mne_icalabel/iclabel/tests/test_utils.py
mne_icalabel/iclabel/utils.py
mne_icalabel/tests/test_label_components.py

Closes #67.
Someone was going to run into it at some point.. turns out it was me from the future: https://github.com/mne-tools/mne-icalabel/blob/a411e45b879be56916681422cfa768a3ca6fa314/mne_icalabel/iclabel/features.py#L173

Fix ICLabel topographic features on ICA fitted with channel selection

---

doc/whats_new.rst
mne_icalabel/iclabel/tests/test_features.py
mne_icalabel/iclabel/tests/test_label_components.py
mne_icalabel/iclabel/tests/test_utils.py
mne_icalabel/iclabel/utils.py
mne_icalabel/tests/test_label_components.py

Fixes the remaining RuntimeWarnings that were issued by the grid interpolation.
Originally reported here: https://mne.discourse.group/t/mne-icalabel-package/5257/5
Fixes the TODO item here: https://github.com/mne-tools/mne-icalabel/blob/15679f1adf9a8c39d3fc208e907f4f3b02a24462/mne_icalabel/iclabel/tests/test_utils.py#L51-L52

Ignore RuntimeWarnings issued by the grid interpolation for ICLabel topographic feature

---

doc/api.rst
doc/conf.py
doc/whats_new.rst
mne_icalabel/features/__init__.py
mne_icalabel/features/tests/test_topomap.py
mne_icalabel/features/topomap.py

The goal is to support only MNE instances in the public API.
The changes were implemented in #73, I am moving them here to start looking into the tests coverage in #93.

[ENH] get_topomap_array is now a private method 

---

.github/workflows/unit_tests.yml
doc/references.bib
pyproject.toml

@adam2392 I was tired of long/messy `references.bib` provided to `sphinxcontrib-bibtex` in doc-builds, so I made this util a few days ago. It's basically a simpler equivalent of `black` / `isort` for BibTex files.
It has an auto-format command (`bibclean file.bib`) and a check command (`bibclean-check file.bib`, added to the style CI). Behavior can be configured in `pyproject.toml`. The check makes sure:
- There are no duplicates (checked both by entry-key and by `hash((author, title, year))`)
- That `bibclean` was run -> i.e. the file is correctly formatted: sorted by cite-key, fields alphabetically sorted, DOI or URL (not both, DOI preferred), and irrelevant fields have been removed.
Not that big of a deal on this project with only 2 elements in `references.bib`, but doesn't hurt to add …

Add bibclean static-check/auto-format for references.bib

---

.github/workflows/unit_tests.yml
doc/conf.py
mne_icalabel/features/tests/test_topomap.py

The numpy link to the `dev` doc is not valid anymore. 
I replaced both links for numpy and scipy with the current valid ones for the `stable` documentation.

[MNT] Fix intersphinx for numpy/scipy

---

.github/workflows/unit_tests.yml
Makefile
mne_icalabel/iclabel/network.py
mne_icalabel/iclabel/tests/test_network.py
pyproject.toml

PR Description
--------------
Added ONNX support to iclabel. I changed the function `run_iclabel` to include a library parameter. This parameter's default value is set to use PyTorch. I added unit tests to check the network outputs against MATLAB. ONNX is faster to load and more lightweight than PyTorch.
The options for the `library` parameter are `pytorch` and `onnx` so far. It throws a `ValueError` for any other input.
Closes #125.

Added ONNX support

---

mne_icalabel/features/tests/test_topomap.py
mne_icalabel/features/topomap.py

Compatibility following https://github.com/mne-tools/mne-python/pull/11903
Should work with both MNE 1.5 and below and with MNE 1.6 and above.
It's probably worth to cut a release, or cut a release when MNE 1.6 rolls out.

MAINT: Compatiblity for MNE 1.6

---

pyproject.toml

It's gonna work at some point.

Fix missed Qt dependency in stubs workflow

---

doc/changes/authors.inc
doc/changes/latest.rst
mne_icalabel/iclabel/network/tests/test_network.py
mne_icalabel/iclabel/network/torch.py

Closes #192 
If I'm understanding the Torch 2.4 changelog correctly, you just need to explicitly pass a value to `weights_only` to suppress the warning. Since the default is already `False`, I am just explicitly setting it here, so this should be backward compatible
I'll double check that the CI installs 2.4 so we can make sure this fix works. 

FIX: explicitly set weights_only to avoid FutureWarning
